# appveyor.yml
build: off

clone_folder: c:\gopath\src\github.com\shuntaka9576\eliminateToil

environment:
  GOPATH: c:\gopath

stack: go 1.12.3 x64

before_test:
  - choco install make -y
  - choco install sed -y
  - choco install zip -y
  - set GO111MODULE=on
  - scripts\windows\build.bat
  - zip -l -r -j eliminateToilBinary.zip build/* # change to CRLF

test_script:
  - scripts\windows\test.bat
  - dir

artifacts:
  - path: eliminateToilBinary.zip
