# appveyor.yml
build: off

clone_folder: c:\eliminateToil

environment:
  GO111MODULE: on

stack: go 1.12.3 x64

install:
  - cinst -y make sed zip

build_script:
  - scripts\windows\build.bat
  - zip -l -r -j eliminateToilBinary.zip build/* # change to CRLF

test_script:
  - scripts\windows\test.bat
  - dir

artifacts:
  - path: eliminateToilBinary.zip
